default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 12341234
  host: 127.0.0.1

development:
  <<: *default
  database: bookshop

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
